[project]
name = "recognizing-handwritten-digits"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "pytest>=9.0.2",
    "scikit-learn>=1.8.0",
]
